spring:
  main:
    allow-bean-definition-overriding: false
#    web-application-type: none
  profiles:
    active: local

pinpoint:
  modules:
    collector:
      exceptiontrace:
        enabled: true
