spring:
  profiles:
    active: release

server:
  port: 8081

pinpoint:
  modules:
    collector:
      grpc:
        ssl:
          enabled: false
      monitor:
        metric: dropwizard
    realtime:
      enabled: false